python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid2.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid2cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid5.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid5cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid11.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid11cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid14.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid14cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid17.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid17cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid23.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid23cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid26.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid26cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid29.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid29cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid32.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid32cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid43.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid43cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid46.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid46cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid49.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid49cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid52.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid52cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid55.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid55cropped.mp4
python crop_videos.py --vpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid65.mp4 --outpath C:/Users/janhe/PhDwork/PressureDataAnalysis/code_shared/DetectionsPressureTube/YoloV5/yolov5/data/video/Vid65cropped.mp4
pause
